blue_heron/README.md
examples/govee_bulb/README.md
examples/govee_bulb/lib/govee_bulb.ex

There's a couple changes in here:
* Give an example of finding your usb vendor and product ids (otherwise `vid` and `pid` are not very explanatory by themselves)
* Tell the user the specific values they need to set up for their own devices
* Don't rely on both structs being available at compile time
* Since nerves doesn't currently compile with libusb the user would have to manually comment out the `%BlueHeronTransportUSB{}` reference

Adjust documentation for ease-of-use

---

blue_heron/lib/blue_heron/error_code.ex
blue_heron/lib/blue_heron/hci/commands/controller_and_baseband/read_local_name.ex
blue_heron/lib/blue_heron/hci/commands/controller_and_baseband/reset.ex
blue_heron/lib/blue_heron/hci/commands/controller_and_baseband/set_event_mask.ex
blue_heron/lib/blue_heron/hci/commands/controller_and_baseband/write_class_of_device.ex
blue_heron/lib/blue_heron/hci/commands/controller_and_baseband/write_extended_inquiry_response.ex
blue_heron/lib/blue_heron/hci/commands/controller_and_baseband/write_inquiry_mode.ex
blue_heron/lib/blue_heron/hci/commands/controller_and_baseband/write_local_name.ex
blue_heron/lib/blue_heron/hci/commands/controller_and_baseband/write_page_timeout.ex
blue_heron/lib/blue_heron/hci/commands/controller_and_baseband/write_secure_connections_host_support.ex
blue_heron/lib/blue_heron/hci/commands/controller_and_baseband/write_simple_pairing_mode.ex
blue_heron/lib/blue_heron/hci/commands/informational_parameters/read_local_version.ex
blue_heron/lib/blue_heron/hci/commands/le_controller/create_connection_cancel.ex
blue_heron/lib/blue_heron/hci/commands/le_controller/set_scan_enable.ex
blue_heron/lib/blue_heron/hci/commands/link_policy/write_default_link_policy_settings.ex
blue_heron/lib/blue_heron/hci/events/command_status.ex
blue_heron/lib/blue_heron/hci/events/disconnection_complete.ex
blue_heron/lib/blue_heron/hci/events/inquiry_complete.ex
blue_heron/lib/blue_heron/hci/events/le_meta/connection_complete.ex
blue_heron/test/blue_heron/regression/btstack_govee_btled_test.exs

This removes the decoded string status for a few reasons:
1. It could raise if the status was unknown when decoding a response.
This could be ok if a new error is added to the Bluetooth spec like
0x45 was since the code was written.
2. The strings have weird casing: some title case and some not. It seems
really easy to make typos when atoms would be easier to use.
3. One less thing to decode.
Currently status numbers are being passed around like the previous code.  A
subsequent refactor can update to atoms - probably when they're actually used.

Simplify status/error code handling

---

examples/govee/README.md

Without a newline the markdown ``` is treated as raw text rather than being converted to a code block

Fixed dmesg output display in govee example readme

---

README.md
lib/blue_heron/hci_dump/logger.ex

On some systems the /tmp directory is limited in size, so it is nice to disable the logging to this file.
Fixes #58

Allow disabling logging to /tmp/hcidump.pklg file

---

lib/blue_heron/hci/commands/controller_and_baseband/write_scan_enable.ex
lib/blue_heron/hci/transport.ex

Hi. I noticed a few encoded HCI commands in the Transport's default init commands which did not have a corresponding module. I've added a module for the first HCI command in this PR.  If you like, I can add modules for the rest too.

Add WriteScanEnable HCI command

---

lib/blue_heron/att.ex
lib/blue_heron/att/confirmations/handle_value_confirmation.ex
lib/blue_heron/att/indications/handle_value_indication.ex
lib/blue_heron/att/requests/execute_write_request.ex
lib/blue_heron/att/requests/find_by_type_value_request.ex
lib/blue_heron/att/requests/find_information_request.ex
lib/blue_heron/att/requests/prepare_write_request.ex
lib/blue_heron/att/requests/read_blob_request.ex
lib/blue_heron/att/requests/read_request.ex
lib/blue_heron/att/requests/write_request.ex
lib/blue_heron/att/responses/execute_write_response.ex
lib/blue_heron/att/responses/find_by_type_value_response.ex
lib/blue_heron/att/responses/find_information_response.ex
lib/blue_heron/att/responses/prepare_write_response.ex
lib/blue_heron/att/responses/read_blob_response.ex
lib/blue_heron/att/responses/read_response.ex
lib/blue_heron/att/responses/write_response.ex

This adds:
- FindInformationRequest and FindInformationResponse (used in CHARACTERISTIC DESCRIPTOR DISCOVERY procedure)
- ReadRequest, ReadResponse, ReadBlobRequest and ReadBlobResponse (used in CHARACTERISTIC VALUE READ procedure)
- WriteRequest, WriteResponse, PrepareWriteRequest, PrepareWriteResponse, ExecuteWriteRequest and ExecuteWriteResponse  (used in CHARACTERISTIC VALUE WRITE procedure).
- HandleValueIndication and HandleValueConfirmation (used in CHARACTERISTIC VALUE INDICATION procedure)
- FindByTypeValueRequest and FindByTypeValueResponse (used in PRIMARY SERVICE DISCOVERY procedure)
With this, all ATT commands used for GATT should be available in Blue Heron.
I have not added any tests for these, mainly out of laziness 😈 . I have tested half of them on a real device. Let me …

Add some ATT commands required for GATT

---

lib/blue_heron/acl.ex
test/blue_heron/acl_test.exs
test/blue_heron/regression/btstack_govee_btled_test.exs

This fixes serialisation and deserialisation of ACL fields `handle`, `pb`, and `bc`. 
The packet format is described in "5.4.2 HCI ACL Data Packets" in the spec. The graphic is misleading however, as it seems that the 12 bits of handle are contiguous. By looking at packet logs in Wireshark, I've found that it's **not** contiguous.

Fix ACL handle, pb and bc serde

---

lib/blue_heron/acl.ex
lib/blue_heron/gatt/characteristic.ex
lib/blue_heron/gatt/server.ex
lib/blue_heron/gatt/service.ex
lib/peripheral.ex
test/blue_heron/acl_test.exs
test/blue_heron/gatt/server_test.exs
test/blue_heron/regression/btstack_govee_btled_test.exs

This PR adds the base functionality for BLE Peripherals:
- A `BlueHeron.Peripheral` module (and `:gen_statem` process), which is the starting point for library users. It includes:
- An API for configuring, starting and stopping advertising
- Handling of received ATT packets (by forwarding them to `BlueHeron. GATT.Server` and then replying to the client device)
- A `BlueHeron. GATT.Server` module, which handles the generic GATT pieces, and specifies a behaviour for the non-generic pieces: 
- Implements (partial) service discovery for the profile specified by the behaviour implementation.
- Ensures responses fit inside the ATT MTU
- Handles reading/writing of long values without involving the library user
- `BlueHeron. GATT.Characteristic` and `BlueHeron. GATT.Service` modules used by the …

Add peripheral

---

lib/blue_heron/hci/command.ex
lib/blue_heron/hci/commands/le_controller/set_random_address.ex
test/blue_heron/hci/command/le_controller/set_random_address_test.exs

Some Bluetooth modules (like those used in RPi3 and RPi4) do not ship with a Public Device Address devices (MAC address registered with IEEE). Thus, if you just start advertising with the standard config, it will advertise with a "null" address (AA:AA:AA:AA:AA:AA), as seen here:
To avoid this, we need to:
1) Set a Random Device Address (using the command included in this PR)
2) Configure advertising to use the random device address (can be done with the Peripheral API like this: `BlueHeron.Peripheral.set_advertising_parameters(peripheral, %{own_address_type: 0x01})`)
For more info, see the Bluetooth spec at Version 4.2 [Vol 6, Part B], section 1.3 DEVICE ADDRESS.

Add SetRandomAddress HCI command

---

examples/scanner.ex

Raspberry Pi Zero W results:
```elixir
iex(1)> {:ok, pid} = BlueHeronScan.start_link(:uart, %{device: "ttyS0"})
{:ok, #PID<0.10860.0>}
iex(2)> state = :sys.get_state(pid)
%{
ctx: #BlueHeron.Context<0.10861.0>,
devices: %{
4753574963174 => %{
272 => <<64, 10, 1, 0>>,
:name => "Bose AE2 SoundLink",
:time => ~U[2021-09-27 14:48:25.778174Z]
},
48660401950223 => %{
784 => <<64, 16, 2, 48>>,
:name => "LE-Bose Revolve SoundLink",
:time => ~U[2021-09-27 14:48:25.658670Z]
},
110946934216995 => %{
117 => <<66, 4, 1, 128, 102, 100, 231, 216, 154, 89, 35, 102, 231, 216,
154, 89, 34, 1, 62, 0, 0, 0, 0, 0>>,
:time => ~U[2021-09-27 14:48:25.873323Z]
},
181149778439893 => %{
1 => <<1, 1, 4, 28, 196, 90>>,
:name => "GVH5102_EED5",
:time => ~U[2021-09-27 14:48:26.032518Z]
},
181149781445015 => %{
name: …
```

An example scanner to collect Manufacturer Specific Data.

---

lib/peripheral.ex

This PR now contains two related additions to the Peripheral module:
- connection status notifications for the Peripheral's controlling process
- an API for disconnecting a connected Peripheral 
My use case looks like this:
I have my own Bluetooth Manager process in the supervision tree. That process spawns a Peripheral, and enables advertising. When another device connects to my device, I need to start a session. This is handled by the Bluetooth Manager process, which receives the `{BlueHeron.Peripheral, :connected}` message to start the session and `{BlueHeron.Peripheral, :disconnected}` to end the session. If the session times out, it will call `Peripheral.disconnect/1` to close the connection.

Add connection status notifications to peripheral controlling process

---

lib/blue_heron/hci/events/disconnection_complete.ex
lib/blue_heron/hci/events/le_meta/connection_complete.ex

@ConnorRigby found that the [connection handle check in Peripheral](https://github.com/blue-heron/blue_heron/blob/main/lib/peripheral.ex#L132) would consistently fail in his environment.
By looking at the HCI dumps in Wireshark I found that this is because the connection_handle was being deserialized incorrectly in the LEMeta Connection Complete event. The 12 bits that make up the connection_handle are not contiguous - see also https://github.com/blue-heron/blue_heron/pull/72.

Fix connection_handle serde in HCI events

---

lib/blue_heron/att/responses/error_response.ex
lib/blue_heron/gatt/characteristic.ex
lib/blue_heron/gatt/server.ex

This change adds permission configuration to GATT characteristics. The permissions. If permissions are required a error response is returned.
This change does not implement pairing, bonding or authentication.
Signed-off-by: Markus Hutzler <markus@keeplabs.com>

gatt: Allow configure permissions

---

lib/blue_heron/gatt/server.ex
lib/blue_heron/hci/command.ex
lib/blue_heron/hci/commands/informational_parameters/read_bd_addr.ex
lib/blue_heron/hci/commands/informational_parameters/read_local_supported_commands.ex
lib/blue_heron/hci/commands/le_controller/long_term_key_request_negative_reply.ex
lib/blue_heron/hci/commands/le_controller/long_term_key_request_reply.ex
lib/blue_heron/hci/commands/link_control/authentication_requested.ex
lib/blue_heron/hci/commands/link_control/set_connection_encryption.ex
lib/blue_heron/hci/event.ex
lib/blue_heron/hci/events/encryption_change.ex
lib/blue_heron/hci/events/le_meta/long_term_key_request.ex
lib/blue_heron/hci/events/number_of_completed_packets.ex
lib/blue_heron/hci/transport.ex
lib/blue_heron/hci_dump/logger.ex
lib/blue_heron/peripheral.ex
lib/blue_heron/smp.ex
lib/blue_heron/smp/keys.ex
mix.exs

This change adds the security manager and all required HCI commands and events.
The security manager only implements LE legacy passkey pairing with the following restrictions and known issues:
- EDIV LTK and other material from the central are not stored. Only the central can re-encrypt the connection, this is no issue as the peripheral simply replies with "encryption required" and lets the central do its job.
- Some edge cases are not covered.
Use this change as en experimental implementation of LE legacy pairing.

smp: Add Security Manager Protocol Module

---

lib/blue_heron/peripheral.ex

This change fixes an issue where old references to `smp` are used.

smp: Fix old references

---

lib/blue_heron/att/responses/read_by_type_response.ex
lib/blue_heron/gatt/server.ex

This change fixes an issue where `ATT_READ_BY_TYPE_RSP` PDU did not contain the value of the characteristic selected. Bluetooth specification "4.8.2 Read Using Characteristic UUID" defines that the value of the characteristic is added to the PDU if only one characteristic is selected.
This issue caused empty values in the iOS device list and passkey entry form as iOS is using this method to read the devices name before characteristics are discovered.

read by type: Fix implementation

---

lib/blue_heron/hci/command.ex
lib/blue_heron/hci/commands/le_controller/set_advertising_data.ex
lib/blue_heron/hci/commands/le_controller/set_scan_response_data.ex
lib/blue_heron/peripheral.ex

fixes #108 
This fixes the unchecked 31 byte length of advertising_data and adds a new function to set scan response data which allows an additional 31 bytes of data to be sent when a central scans for a peripheral

peripheral: add set_scan_response_data

---

lib/blue_heron/hci/transport.ex

This PR introduces a fix about AdverstisingReport events that were not sent to the process as shown in the #111 issue. 
I've struggled to set up a unit test about it, so I'm open to advices 😄 .
Thanks.

fix: send advertising report to the process

---

CHANGELOG.md
mix.exs

* Enhancements
* `:blue_heron` is now it's own application
* Rewrote `BlueHeron.HCI.Transport` to support the new supervision structure
* Enable SMP by default
* Persist GATT into a `PropertyTable` to allow for better error handling
* Creating a Peripheral is now a little simpler and supervised
* Added Broadcaster role
* Depreciations
* Removed `BlueHeron.Context`
* Removed `BlueHeronTransportUART` and `BlueHeronTransportUSB`

Release v0.5.0

---

lib/blue_heron/hci/transport.ex
lib/blue_heron/hci/transport/uart.ex

This fixes an issue on certain radios where they will respond with garbage data during initialization and throw off a frame or two, enough to stall setup forever.

Flush transport on timeout during setup

---

mix.exs

This matches BlueHeron's Elixir requirement to match that of [Nerves](https://github.com/nerves-project/nerves/blob/a59eb469c38cc5468c6033de723227e92262469b/mix.exs#L11C1-L11C92)

Lossen up Elixir version requirement

---

CHANGELOG.md
mix.exs

* Enhancements
* Changed the Elixir version requirement to match Nerves.
This fixes an unneeded warning on Elixir versions older than 1.18.

v0.5.2 Release

---

mix.exs
mix.lock

v0.3.0 was technically a breaking change, but not for BlueHeron's
minimal use of it. This allows both versions to be used so people can
use v0.3.0 if they want with BlueHeron.

Relax property_table dependency to support v0.3.0
